### ISSUE TITLE
Access Anywhere Upgrade -  Sprite Freeze

### ISSUE THREAD

**Issue by Uwazouri** [Uwazouri/ExpandedFridge#6]
Report on clicking off screen (for example to check stardew wiki) causes bug.
Investigate, confirm and fix.

**Comment by Uwazouri** [comment]
Message from original finder:

Good morning! I've got an odd one. Running with the "access fridge anywhere" purchased. If I click off screen - adjust volume, look something up, etc. - my sprite freezes, I can't access the fridge, the escape key doesn't bring up the menu, and the IG chat bar opens {but I can't interact with it}.

Game runs fine without this mod installed and other mods active.

Here's my SMAPI log: https://log.smapi.io/WC4TjeFa

I also got the error to show in the SMAPI run window: {sorry this is a mess, copied from the run window to notepad}

[game] An error occured in the base update loop: System.NullReferenceException: Object reference not set to an instance of an object.
at ExpandedFridge.ExpandedFridgeHub.ClearEmptyStacks() in F:\Library\Documents\ExpanedFridgeSolution\ExpandedFridge\ExpandedFridge\Extensions\ExpandedFridgeHub.cs:line 376
at ExpandedFridge.ExpandedFridgeHub.ClearReferences() in F:\Library\Documents\ExpanedFridgeSolution\ExpandedFridge\ExpandedFridge\Extensions\ExpandedFridgeHub.cs:line 400
at ExpandedFridge.ExpandedFridgeHub.<checkForAction>b__69_0() in F:\Library\Documents\ExpanedFridgeSolution\ExpandedFridge\ExpandedFridge\Extensions\ExpandedFridgeHub.cs:line 918
at StardewValley.Network.NetMutex.RequestLock(Action acquired, Action failed) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Network\NetMutex.cs:line 47
at ExpandedFridge.ExpandedFridgeHub.checkForAction(Farmer who, Boolean justCheckingForActivity) in F:\Library\Documents\ExpanedFridgeSolution\ExpandedFridge\ExpandedFridge\Extensions\ExpandedFridgeHub.cs:line 916
at StardewValley.Locations.FarmHouse.checkAction(Location tileLocation, Rectangle viewport, Farmer who) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Locations\FarmHouse.cs:line 272
at StardewValley.Game1.tryToCheckAt(Vector2 grabTile, Farmer who) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:line 7904
at StardewValley.Game1.pressActionButton(KeyboardState currentKBState, MouseState currentMouseState, GamePadState currentPadState) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:line 7793
at StardewValley.Game1.<>c__DisplayClass652_0.<UpdateControlInput>b__0() in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:line 10272
at StardewValley.ModHooks.OnGame1_UpdateControlInput(KeyboardState& keyboardState, MouseState& mouseState, GamePadState& gamePadState, Action action) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\ModHooks.cs:line 11
at StardewValley.Game1.UpdateControlInput(GameTime time) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:line 9851
at StardewValley.Game1._update(GameTime gameTime) in C:\Users\gitlab-runner\gitlab-runner\builds\5c0f9387\0\chucklefish\stardewvalley\Farmer\Farmer\Game1.cs:line 2386
at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 899
