### ISSUE TITLE
Animal Husbandry Fridge Inventory Bug

### ISSUE THREAD

**Issue by Uwazouri** [Uwazouri/ExpandedFridge#7]
Bug with Animal Husbandry mod, player reported error and cant access certain ingredients in fridge
Investigate, confirm and fix.

**Comment by Uwazouri** [comment]
Hi there,

Not sure if it's just me, but I've noticed that whenever I mouse over ingredients produced by the animal husbandry mod when either mousing over the ingredient after placing it in the fridge or when I mouse over a recipe that uses any of those ingredients, I get the following error message in SMAPI:

"[SMAPI] The StardewValley.Menus.CraftingPage menu crashed while drawing itself. SMAPI will force it to exit to avoid crashing the game.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at StardewValley.Menus.CraftingPage.draw(SpriteBatch b) in ******\stardewvalley\Farmer\Farmer\Menus\CraftingPage.cs:line 535
at StardewModdingAPI.Framework.SGame.DrawImpl(GameTime gameTime) in ******\SMAPI\Framework\SGame.cs:line 1664".

If this does not appear to be a problem with this mod in particular, I'll be happy to report this on the appropriate mod page for Animal Husbandry, but I had the initial assumption that perhaps the Animal Husbandry ingredients perhaps needed to be referenced in some way by this mod for inclusion in its inventory. In any case, I can no longer do anything with those ingredients in the fridge for the time being as I cannot mouse over them to remove them.

Just wanted to bring awareness!
